# STEP 1: Hold Ctrl (or Cmd on Mac) and CLICK the blue link below to open your browser:
https://microsoftonline.com

###

# STEP 2: Paste the long string found after '?code=' in your browser's address bar here:
@userAuthorizationCode = paste_your_copied_code_here

###

# @name userTokenExchange
# STEP 3: Click 'Send Request' to swap that code for your user access token
POST https://microsoftonline.com HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&client_id=a98249d2-b51b-41d6-9c2a-5dadf7cf276f&code={{userAuthorizationCode}}&redirect_uri=https://pstmn.io

###

@userAuthToken = {{userTokenExchange.response.body.$.access_token}}

### Subsequent request acting as the logged-in user
GET https://localhost:7135/api/values
Authorization: Bearer {{userAuthToken}}