name: BookShelves.Maui Windows CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'release/*'  
    paths:
      # - 'BookShelves.iOS/**'
      # - 'BookShelves.Mac/**'
      # - 'src/BookShelves.WinUI/**'
      - 'src/BookShelves.Maui/**'
      - 'src/BookShelves.Shared/**'
      - '**/*build.props'
      - '**/GitVersion.yml'
      - '.github/workflows/BookShelvesWinUI-CI-Main.yml'
  pull_request:
    types: [opened, synchronize]
    paths:
      # - 'BookShelves.iOS/**'
      # - 'BookShelves.Mac/**'
      # - 'src/BookShelves.WinUI/**'
      - 'src/BookShelves.Maui/**'
      - 'src/BookShelves.Shared/**'
      - '**/*build.props'      
      - '.github/workflows/BookShelvesWinUI-CI-Main.yml'
    branches: 
      - '**'

jobs:
  windows-build-windows:
    runs-on: windows-latest
    timeout-minutes: 45
    env:
      PROJPATH: 'src/BookShelves.Maui'
      CSPROJ: 'BookShelves.Maui.csproj'
      # CSPROJ: 'src/BookShelves.Maui/BookShelves.Maui.csproj'
      PUBLISH_PATH: '${{ github.workspace }}/publish-output'
      WINDOWS_ARTIFACTS_PATH: 'artifacts_windows'
      BUILD_LOG_FILE: 'windows.binlog'
      DOTNET_SDK_VERSION: '10.0.x'
    defaults:
      run:
        working-directory: ${{env.PROJPATH}}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.7.0
        with:
          versionSpec: '6.8.x'

      - name: Determine Version
        id: version_step # step id used as a reference for output values
        uses: gittools/actions/gitversion/execute@v4.7.0
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{env.DOTNET_SDK_VERSION}}

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v3

      - name: Install MAUI Workloads
        # run: |
        #  dotnet workload install maui --source https://api.nuget.org/v3/index.json
        run: dotnet workload restore # ${{env.PROJPATH}} # ${{env.CSPROJ}}
        working-directory: ${{env.PROJPATH}}

      - name: Decrypt PFX File
        run: |
          echo "${{ secrets.WINDOWS_PFX_FILE }}" > cert.pfx.asc
          certutil -decode cert.pfx.asc cert.pfx

      - name: Add Cert to Store
        run: certutil -user -q -p ${{ secrets.WINDOWS_PFX_PASSWORD }} -importpfx cert.pfx NoRoot

      - name: Create publish folder
        shell: pwsh
        run: |
          cd ${{ github.workspace }}
          mkdir -p ${{ env.PUBLISH_PATH }}

      - name: Build MAUI Mobile app
        shell: pwsh
        run: |
          dotnet publish ${{env.CSPROJ}} `
            -v minimal `
            -bl:${{env.BUILD_LOG_FILE}} `
            -f net10.0-windows10.0.19041.0 `
            -c Release `
            -o ${{ env.PUBLISH_PATH }} `
            --self-contained false `
            -p:RuntimeIdentifierOverride=win10-x64 `
            -p:InvariantGlobalization=true `
            /p:GenerateTestArtifacts=false `
            /p:WindowsPackageType=MSIX `
            /p:GenerateAppxPackageOnBuild=true `
            /p:AppxPackageSigningEnabled=true `
            /p:PackageCertificateThumbprint="${{ secrets.WINDOWS_PFX_THUMBPRINT }}"
          # -v options are quiet, minimal, normal, detailed, diagnostic

      - name: Show project folder content
        shell: pwsh
        run: |
          Get-Childitem -Path . -Include *.* -File -Recurse

      - name: Show publish folder content
        shell: pwsh
        run: |
          Get-Childitem -Path ${{ env.PUBLISH_PATH }} -Include *.* -File -Recurse

      - name: Archive build log
        uses: actions/upload-artifact@v7
        with:
          name: logs
          path: '${{env.PROJPATH}}\${{env.BUILD_LOG_FILE}}'

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v7
        with:
          name: MAUI-Windows-App
          path: |
            ${{env.PROJPATH}}\AppPackages\**\*.msix
            ${{env.PROJPATH}}\AppPackages\**\*.msixbundle

      # - name: Create artifacts folder
      #   shell: pwsh
      #   run: |
      #     cd ${{ github.workspace }}
      #     mkdir -p ${{ env.WINDOWS_ARTIFACTS_PATH }}

      # - name: Copy WinUI msix package
      #   shell: pwsh
      #   run: |
      #     Get-Childitem -Path ${{ github.workspace }} -Include BookShelves*.msix* -File -Recurse | Copy-Item -Destination ${{ env.WINDOWS_ARTIFACTS_PATH }}
      
      # - name: Archive build artifact
      #   uses: actions/upload-artifact@v7
      #   with:
      #     name: 'win-x64 msix'
      #     path: ${{ env.WINDOWS_ARTIFACTS_PATH }} '${{ github.workspace }}/src/BookShelves.WinUI/bin/Release/net8.0-windows10.0.19041.0/win10-x64/AppPackages/*'
      #     compression-level: 0