name: BookShelves.Maui IOS CI Dev

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      # - 'main'
      - 'release/*'
    paths:
      # - 'src/BookShelves.Droid/**'
      # - 'BookShelves.iOS/**'
      # - 'BookShelves.Mac/**'
      # - 'src/BookShelves.WinUI/**'
      - 'src/BookShelves.Maui/**'
      - 'src/BookShelves.Shared/**'
      - '**/*build.props'
      - '**/GitVersion.yml'
      - '.github/workflows/BookShelvesIOS-CI-Dev.yml'
  # pull_request:
  #   types: [opened, synchronize]
  #   paths:
  #   #- 'src/BookShelves.Droid/**'
  #   #- 'BookShelves.iOS/**'
  #   #- 'BookShelves.Mac/**'
  #   #- 'src/BookShelves.WinUI/**'
  #     - 'src/BookShelves.Maui/**'
  #     - 'src/BookShelves.Shared/**'
  #     - '**/*build.props'      
  #     - '.github/workflows/BookShelvesIOS-CI-Main.yml'
  #   branches: 
  #     - '**'

concurrency:
  group: maui-ios-dev-${{github.ref}}
  cancel-in-progress: true

jobs:
  mac-build-ios:
    runs-on: macos-26
    timeout-minutes: 60
    env:
      PROJPATH: 'src/BookShelves.Maui'
      # CSPROJ: 'src/BookShelves.Maui/BookShelves.Maui.csproj'
      CSPROJ: 'BookShelves.Maui.csproj'
      PUBLISH_PATH: '${{ github.workspace }}/publish-output'
      IOS_ARTIFACTS_PATH: 'artifacts_ios'
      BUILD_LOG_FILE: 'ios.binlog'
      BUNDLE_ID: 'com.azmoore.bookshelves.maui'
      CODESIGN_PROVISION: 'BookShelves Test Profile'
      CODESIGN_KEY: 'iOS Distribution'
      DOTNET_VERSION: 'net10.0'
      # DOTNET_SDK_VERSION: '9.0.306'
      # dotnet workload install ios --version 9.0.203
      DOTNET_SDK_VERSION: '10.0.x'
      #DOTNET_SDK_VERSION: '10.0.102'
      # DOTNET_SDK_VERSION: '9.0.310'
      # DOTNET_SDK_VERSION: '9.0.x'
      RELEASE_CONFIGURATION: 'Release'
      # XCODE_VERSION: '16.4'
      XCODE_VERSION: '26.4.1'
      # XCODE_VERSION: '18.6'
    defaults:
      run:
        working-directory: ${{env.PROJPATH}}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.7.0
        with:
          versionSpec: '6.8.x'

      - name: Determine Version
        id: version_step # step id used as a reference for output values
        uses: gittools/actions/gitversion/execute@v4.7.0

      - name: xcode diags 1
        run: |
            echo Mac OS version: $(sw_vers -productVersion)
            echo Installed Xcode versions:
            ls /Applications | grep 'Xcode'
            echo Currently selected Xcode:
            xcrun xcode-select --print-path

      # Select your required version
      - name: Select Xcode ${{env.XCODE_VERSION}}
        run: sudo xcode-select -s /Applications/Xcode_${{env.XCODE_VERSION}}.app #/Contents/Developer

      - name: Verify Xcode version
        run: xcodebuild -version
      
      # - name: xcode diags 2
      #   run: |
      #       echo Currently selected Xcode:
      #       xcrun xcode-select --print-pat

      - name: Add Xcode developer tools to PATH
        run: export PATH="/Applications/Xcode_${{env.XCODE_VERSION}}.app/Contents/Developer/usr/bin:$PATH"

      - name: Set some env variables (CURRENT_DATE, CURRENT_TIME, ASSEMBLY_BUILD_NUMBER)
        run: |
            echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
            echo "CURRENT_TIME=$(date +'%H:%M:%S')" >> $GITHUB_ENV
            echo "ASSEMBLY_BUILD_NUMBER=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: ${{env.PROJPATH}}/global.json
          # dotnet-version: ${{env.DOTNET_SDK_VERSION}}
          # include-prerelease: true

      # - name: Add msbuild to PATH
      #   uses: microsoft/setup-msbuild@v2

      # - name: Change Directory
      #   run: cd ${{env.PROJPATH}}

      # - name: Change Directory
      #   run: ls -al

      - name: Restore Workloads
        run: dotnet workload restore # ${{env.PROJPATH}} # ${{env.CSPROJ}}
        working-directory: ${{env.PROJPATH}}

      # - name: Install MAUI Workloads
      #   run: |
      #     dotnet workload install maui --source https://api.nuget.org/v3/index.json

      - name: Cert Info 1
        env:
          CERTIFICATE_BASE64: ${{secrets.IOS_DIST_CERTIFICATES_P12}}
        run: |
          echo $CERTIFICATE_BASE64 | base64 --decode > cert.p12

      - name: Cert Info 2
        run: |
          openssl pkcs12 -in cert.p12 -passin pass:${{secrets.IOS_DIST_CERTIFICATES_P12_PASSWORD}} -info -nokeys

      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v7
        with:
          p12-file-base64: ${{secrets.IOS_DIST_CERTIFICATES_P12}}
          p12-password: ${{secrets.IOS_DIST_CERTIFICATES_P12_PASSWORD}}
      
      # - name: Issuer ID
      #   run: |
      #     echo ${{ secrets.APPLE_APPSTORE_ISSUER_ID }} | sed 's/./& /g'
      # - name: Key ID
      #   run: |
      #     echo ${{ secrets.APPLE_APPSTORE_KEY_ID }} | sed 's/./& /g'
      # - name: Priv K
      #   run: |
      #     echo "${{ secrets.APPLE_APPSTORE_PRIVATE_KEY }}" | sed 's/./& /g'

      - name: Download Apple Provisioning Profiles
        uses: Apple-Actions/download-provisioning-profiles@v6
        with:
          bundle-id: ${{env.BUNDLE_ID}}
          issuer-id: ${{secrets.APPLE_APPSTORE_ISSUER_ID}}
          api-key-id: ${{secrets.APPLE_APPSTORE_KEY_ID}}
          api-private-key: ${{secrets.APPLE_APPSTORE_PRIVATE_KEY}}

      - name: Verify Xcode Simulators
        run: xcrun simctl list devices

      - name: Verify Dotnet SDKs
        run: dotnet --list-sdks

      - name: Verify Dotnet Version
        run: dotnet --version

      - name: Verify Dotnet Runtimes
        run: dotnet --list-runtimes

      - name: NuGet Restore
        run: dotnet restore ${{env.CSPROJ}}
        working-directory: ${{env.PROJPATH}}

      - name: Create publish folder
        shell: pwsh
        run: |
          cd ${{ github.workspace }}
          mkdir -p ${{env.PUBLISH_PATH}}

      - name: Publish MAUI Mobile app
        shell: pwsh
        run: |
          dotnet `
            publish `
            ${{env.CSPROJ}} `
            -f ${{env.DOTNET_VERSION}}-ios `
            -p:RuntimeIdentifier=ios-arm64 `
            -c ${{env.RELEASE_CONFIGURATION}} `
            -o ${{env.PUBLISH_PATH}} `
            -v normal `
            /p:ArchiveOnBuild=true `
            /p:ApplicationVersion=${{env.ASSEMBLY_BUILD_NUMBER}} `
            /p:CodesignKey="${{env.CODESIGN_KEY}}" `
            /p:CodesignProvision="${{env.CODESIGN_PROVISION}}" `
            /p:MtouchUseLlvm=false
            # --no-restore `
            # -bl:${{env.BUILD_LOG_FILE}} `
            # --self-contained false -p:RuntimeIdentifierOverride=android-x64 /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="${{ secrets.WINDOWS_PFX_THUMBPRINT }}"
            # dotnet publish ${{env.CSPROJ}} -bl:mobile.binlog -c Release -r win10-x64 -p:RuntimeIdentifierOverride=win10-x64 -p:WindowsPackageType=None
        working-directory: ${{env.PROJPATH}}
      
      # - name: Show publish folder content 
      #   shell: pwsh
      #   run: |
      #     cd '${{ github.workspace }}'
      #     Get-Childitem -Path ${{ github.workspace }} -Include *BookShelves*.ipa -File -Recurse
      #     Get-Childitem -Path ${{ github.workspace }} -Include *.plist -File -Recurse

      - name: Show publish folder content
        shell: pwsh
        run: |
          Get-Childitem -Path ${{env.PUBLISH_PATH}} -Include *.* -File -Recurse

      # - name: version
      #   run: echo "::set-output name=version::$(./bin/azblogfilter --version)"
      #   id: version
 
      #- name: release
      #  uses: actions/create-release@v1
      #  id: create_release
      #  with:
      #    draft: true
      #    prerelease: true
      #    release_name: ${{ env.ASSEMBLY_BUILD_NUMBER }}
      #    tag_name: ${{ env.ASSEMBLY_BUILD_NUMBER }}
      #    # body_path: 'TEST TAG' #CHANGELOG.md
      #  env:
      #    GITHUB_TOKEN: ${{ github.token }}

      - name: Locate IPA
        # if: ${{ github.event_name == 'workflow_dispatch' }}
        id: findipa
        run: |
          IPA_PATH=$(find ${{env.PUBLISH_PATH}} -maxdepth 1 -name '*.ipa' | head -n1)
          # IPA_PATH=$(find MyScoreBoardMaui/bin/${{env.RELEASE_CONFIGURATION}}/${{env.DOTNET_VERSION}}-ios/${{env.RUNTIME_ID}}/publish -maxdepth 1 -name '*.ipa' | head -n1)
          if [ -z "$IPA_PATH" ]; then
            echo 'IPA not found' >&2
            exit 1
          fi
          echo "ipa=$IPA_PATH" >> $GITHUB_OUTPUT

      - name: 'Upload app to TestFlight'
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        uses: apple-actions/upload-testflight-build@v5
        with:
          app-type: 'ios'
          app-path: ${{ steps.findipa.outputs.ipa }}
          issuer-id: ${{secrets.APPLE_APPSTORE_ISSUER_ID}}
          api-key-id: ${{secrets.APPLE_APPSTORE_KEY_ID}}
          api-private-key: ${{secrets.APPLE_APPSTORE_PRIVATE_KEY}}

      # - name: Archive build log
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: logs
      #     path: '${{env.BUILD_LOG_FILE}}'

      # - name: Create artifacts folder
      #   shell: pwsh
      #   run: |
      #     cd ${{ github.workspace }}
      #     mkdir -p ${{ env.IOS_ARTIFACTS_PATH }}

      # - name: Copy IOS IPA package
      #   shell: pwsh
      #   run: |
      #       ${{ steps.findipa.outputs.ipa }}
      #     Get-Childitem -Path ${{ github.workspace }} -Include *BookShelves*.ipa -File -Recurse | Copy-Item -Destination ${{ env.IOS_ARTIFACTS_PATH }}
      
      - name: Archive build artifact
        uses: actions/upload-artifact@v7
        with:
          name: 'ios ipa'
          path: ${{steps.findipa.outputs.ipa}} #${{ env.IOS_ARTIFACTS_PATH }} #'${{ github.workspace }}/src/BookShelves.WinUI/bin/Release/net8.0-windows10.0.19041.0/win10-x64/AppPackages/*'
          compression-level: 0

      # # BUILD
      # - name: Restore dependencies
      #   shell: pwsh
      #   run: |
      #     dotnet restore ${{ env.csproj }}

      # - name: Build Maui WinUI project
      #   shell: pwsh
      #   run: |
      #     dotnet publish ${{ env.csproj }} -c Release -f net7.0-windows10.0.19041.0

      # - name: Create artifacts folder
      #   shell: pwsh
      #   run: |
      #      cd ${{ github.workspace }}
      #      mkdir -p ${{ env.WINDOWS_ARTIFACTS_PATH }}

      # - name: Copy WinUI msix package
      #   shell: pwsh
      #   run: |
      #      Get-Childitem �Path ${{ github.workspace }} -Include *.msix -File -Recurse | Copy-Item -Destination ${{ env.WINDOWS_ARTIFACTS_PATH }}

      # #POST-BUILD
      # - name: Publish build artifacts
      #   uses: actions/upload-artifact@v2
      #   with:     
      #     name: "WinUI .NET MAUI artifacts" 
      #     path: "${{ env.WINDOWS_ARTIFACTS_PATH }}/*"
      #     if-no-files-found: error
      #     retention-days: 90
