name: BookShelvesApp .NET MAUI Blazor CI

on:
  push:
    paths:
      - 'BookShelvesApp/**'
      - 'SharedModels/**'
      - 'SharedRazorClassFiles/**'
      - '**/*build.props'  
      - '.github/workflows/BookShelvesApp-CI-Main.yml'
    branches:
      - main
      - dev*  
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - 'BookShelvesApp/**'
      - 'SharedModels/**'
      - 'SharedRazorClassFiles/**'
      - '**/*build.props'      
      - '.github/workflows/BookShelvesApp-CI-Main.yml'
    branches: 
      - '**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CSPROJ: BookShelvesApp/BookShelvesApp.csproj
  WINDOWS_ARTIFACTS_PATH: "artifacts_windows"

jobs:
  windows-build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
          include-prerelease: true

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Install MAUI Workloads
        run: |
          dotnet workload install maui --source https://api.nuget.org/v3/index.json

      - name: Build MAUI Mobile app
        shell: pwsh
        run: |
          dotnet build ${{env.csproj}} -bl:mobile.binlog

      - name: Archive build log
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: '*.binlog'
